import type { ContentItem, DashboardCard } from "../types";

export const contentItems: ContentItem[] = [
  {
    id: "novel-archive",
    title: "Novel reading archive",
    type: "document",
    source: "note",
    location: "D:/Library/Novels",
    collection: "Novels",
    tags: ["reading", "archive"],
    accent: "#b7791f",
    summary: "A long-form reading shelf for novels and text files.",
    textContent:
      "This is a sample reading page. Later, local txt/md/epub files can be opened here with custom width, theme, and line height.",
    isFavorite: true,
    openCount: 0,
    createdAt: "2026-07-08T00:00:00.000Z",
    updatedAt: "2026-07-08T00:00:00.000Z",
  },
  {
    id: "lecture-react",
    title: "React lecture materials",
    type: "video",
    source: "path",
    location: "D:/Study/React",
    collection: "Lectures",
    tags: ["frontend", "lecture"],
    accent: "#2563eb",
    summary: "Stable lecture videos and notes.",
    isFavorite: true,
    openCount: 0,
    createdAt: "2026-07-08T00:00:00.000Z",
    updatedAt: "2026-07-08T00:00:00.000Z",
  },
  {
    id: "music-focus",
    title: "Focus music folder",
    type: "audio",
    source: "path",
    location: "D:/Music/Focus",
    collection: "Music",
    tags: ["focus", "playlist"],
    accent: "#7c3aed",
    summary: "Local audio for focus sessions.",
    isFavorite: false,
    openCount: 0,
    createdAt: "2026-07-08T00:00:00.000Z",
    updatedAt: "2026-07-08T00:00:00.000Z",
  },
  {
    id: "references",
    title: "Saved reference links",
    type: "link",
    source: "url",
    location: "https://example.com",
    collection: "Links",
    tags: ["reference", "later"],
    accent: "#059669",
    summary: "Links saved outside the browser bookmark bar.",
    isFavorite: true,
    openCount: 0,
    createdAt: "2026-07-08T00:00:00.000Z",
    updatedAt: "2026-07-08T00:00:00.000Z",
  },
];

export const dashboardCards: DashboardCard[] = [
  {
    id: "continue-reading",
    title: "Continue reading",
    description: "Recent novels and long-form documents",
    variant: "wide",
    itemId: "novel-archive",
  },
  {
    id: "lecture-shelf",
    title: "Lecture shelf",
    description: "Stable learning videos and notes",
    variant: "standard",
    itemId: "lecture-react",
  },
  {
    id: "focus-music",
    title: "Music shelf",
    description: "Local audio for focus sessions",
    variant: "standard",
    itemId: "music-focus",
  },
  {
    id: "saved-links",
    title: "Saved links",
    description: "Reference links beyond browser bookmarks",
    variant: "tall",
    itemId: "references",
  },
];
