import { getSafeExternalUrl } from "./urlSafety";

/**
 * What a YouTube or YouTube Music address points at. Everything here is read
 * out of the address itself — no account, no API key, and no network request.
 */
export type YoutubeLinkKind = "track" | "video" | "album" | "playlist" | "artist" | "unknown";

export interface YoutubeLinkInfo {
  kind: YoutubeLinkKind;
  /** Present for anything that plays a single item. */
  videoId?: string;
  /** Present for playlist and album addresses, and for a track opened inside one. */
  playlistId?: string;
  /** YouTube Music album browse id (`MPREb_…`). */
  browseId?: string;
  /** Channel or artist id (`UC…`). */
  channelId?: string;
  isMusic: boolean;
}

const MUSIC_HOSTS = new Set(["music.youtube.com"]);
const WATCH_HOSTS = new Set(["youtube.com", "www.youtube.com", "m.youtube.com", "music.youtube.com"]);
const SHORT_HOSTS = new Set(["youtu.be", "www.youtu.be"]);

// Ids are opaque, so these only check the shape well enough to reject junk and
// to avoid putting arbitrary text into a thumbnail URL.
const VIDEO_ID_PATTERN = /^[\w-]{11}$/;
const PLAYLIST_ID_PATTERN = /^[\w-]{2,64}$/;
const BROWSE_ID_PATTERN = /^MPRE[\w-]{2,64}$/;
const CHANNEL_ID_PATTERN = /^UC[\w-]{10,64}$/;

/**
 * Album playlists generated by YouTube Music carry this prefix, which is what
 * separates "an album" from "a playlist someone assembled".
 */
const ALBUM_PLAYLIST_PREFIX = "OLAK5uy_";

function parsedUrl(rawUrl: string): URL | null {
  const safe = getSafeExternalUrl(rawUrl);
  if (!safe) return null;
  try {
    return new URL(safe);
  } catch {
    return null;
  }
}

function matched(value: string | null, pattern: RegExp): string | undefined {
  if (!value) return undefined;
  return pattern.test(value) ? value : undefined;
}

function playlistKind(playlistId: string): YoutubeLinkKind {
  return playlistId.startsWith(ALBUM_PLAYLIST_PREFIX) ? "album" : "playlist";
}

/**
 * Reads a YouTube or YouTube Music address. Returns null for anything else,
 * including malformed or non-http addresses.
 */
export function parseYoutubeLink(rawUrl: string): YoutubeLinkInfo | null {
  const url = parsedUrl(rawUrl);
  if (!url) return null;

  const host = url.hostname.toLowerCase();
  const isMusic = MUSIC_HOSTS.has(host);
  const isWatchHost = WATCH_HOSTS.has(host) || host.endsWith(".youtube.com");
  const isShortHost = SHORT_HOSTS.has(host);
  if (!isWatchHost && !isShortHost) return null;

  const segments = url.pathname.split("/").filter(Boolean);

  if (isShortHost) {
    const videoId = matched(segments[0] ?? null, VIDEO_ID_PATTERN);
    const playlistId = matched(url.searchParams.get("list"), PLAYLIST_ID_PATTERN);
    if (!videoId) return { kind: "unknown", isMusic: false };
    return { kind: "video", videoId, playlistId, isMusic: false };
  }

  if (segments[0] === "watch") {
    const videoId = matched(url.searchParams.get("v"), VIDEO_ID_PATTERN);
    const playlistId = matched(url.searchParams.get("list"), PLAYLIST_ID_PATTERN);
    if (!videoId) return { kind: "unknown", isMusic };
    return { kind: isMusic ? "track" : "video", videoId, playlistId, isMusic };
  }

  if (segments[0] === "playlist") {
    const playlistId = matched(url.searchParams.get("list"), PLAYLIST_ID_PATTERN);
    if (!playlistId) return { kind: "unknown", isMusic };
    return { kind: playlistKind(playlistId), playlistId, isMusic };
  }

  // music.youtube.com/browse/MPREb_… is how YouTube Music addresses an album.
  if (segments[0] === "browse" && segments[1]) {
    const browseId = matched(segments[1], BROWSE_ID_PATTERN);
    if (browseId) return { kind: "album", browseId, isMusic };
    const channelId = matched(segments[1], CHANNEL_ID_PATTERN);
    if (channelId) return { kind: "artist", channelId, isMusic };
    return { kind: "unknown", isMusic };
  }

  if (segments[0] === "channel" && segments[1]) {
    const channelId = matched(segments[1], CHANNEL_ID_PATTERN);
    if (!channelId) return { kind: "unknown", isMusic };
    return { kind: "artist", channelId, isMusic };
  }

  return { kind: "unknown", isMusic };
}

/**
 * Builds the still-image URL for a video id. The address is assembled locally,
 * but loading it does reach Google, so callers must respect the link preview
 * setting before using it.
 */
export function youtubeThumbnailUrl(videoId: string): string | null {
  if (!VIDEO_ID_PATTERN.test(videoId)) return null;
  return `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`;
}

/** The thumbnail for a parsed link, when it has one. */
export function youtubeLinkThumbnail(info: YoutubeLinkInfo): string | null {
  return info.videoId ? youtubeThumbnailUrl(info.videoId) : null;
}

/** Extra tags describing what the address points at. */
export function youtubeLinkTags(info: YoutubeLinkInfo): string[] {
  switch (info.kind) {
    case "track":
      return ["yt-track"];
    case "album":
      return ["yt-album"];
    case "playlist":
      return ["yt-playlist"];
    case "artist":
      return ["yt-artist"];
    default:
      return [];
  }
}
